import { Asset } from "./types";

/**
 * Placeholder data so the page renders end-to-end.
 * Replace with a real fetch (Firestore, REST, etc.) once the
 * Asset Management backend is wired up — the shape matches `Asset`
 * in lib/types.ts so the swap is a drop-in.
 */
export const MOCK_ASSETS: Asset[] = [
  {
    id: "a001",
    code: "A001",
    name: "Desktop AOI",
    group: "Office Group",
    purchaseDate: "2023-08-20",
    quantityAllocated: 0,
    inventory: 15,
    originalPrice: 1125000,
    unit: "Electronics",
    department: "Development/Engineering",
    status: "using",
  },
  {
    id: "a002",
    code: "A002",
    name: "Dell Latitude 5440",
    group: "Laptops",
    purchaseDate: "2024-02-11",
    quantityAllocated: 8,
    inventory: 2,
    originalPrice: 98000,
    unit: "Electronics",
    department: "Development/Engineering",
    status: "using",
  },
  {
    id: "a003",
    code: "A003",
    name: "Office Chair — Ergo",
    group: "Furniture",
    purchaseDate: "2022-11-03",
    quantityAllocated: 20,
    inventory: 0,
    originalPrice: 12500,
    unit: "Piece",
    department: "Admin",
    status: "not_used",
  },
  {
    id: "a004",
    code: "A004",
    name: "HP LaserJet Pro M404",
    group: "Office Group",
    purchaseDate: "2021-05-30",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 34500,
    unit: "Electronics",
    department: "Admin",
    status: "warranty_repair",
  },
  {
    id: "a005",
    code: "A005",
    name: "Projector — Epson EB-X05",
    group: "Office Group",
    purchaseDate: "2020-09-14",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 42000,
    unit: "Electronics",
    department: "Admin",
    status: "broken",
  },
  {
    id: "a006",
    code: "A006",
    name: "iPhone 13 — Field Kit",
    group: "Mobile Devices",
    purchaseDate: "2023-01-18",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 89000,
    unit: "Electronics",
    department: "Field Reports",
    status: "report_lost",
  },
  {
    id: "a007",
    code: "A007",
    name: "Meeting Room Table Set",
    group: "Furniture",
    purchaseDate: "2019-07-02",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 65000,
    unit: "Set",
    department: "Admin",
    status: "liquidation",
  },
];

export const ASSET_STATUS_LABEL: Record<Asset["status"], string> = {
  not_used: "Not used yet",
  using: "Using",
  liquidation: "Liquidation",
  warranty_repair: "Warranty Repair",
  report_lost: "Report lost",
  broken: "Broken",
};
