import { Asset } from "./types";

/**
 * Placeholder data so the page renders end-to-end.
 * Replace with a real fetch (Firestore, REST, etc.) once the
 * Asset Management backend is wired up — the shape matches `Asset`
 * in lib/types.ts so the swap is a drop-in.
 */
export const MOCK_ASSETS: Asset[] = [
  {
    id: "a001",
    code: "A001",
    name: "iPhone 13",
    group: "Mobile",
    purchaseDate: "2023-08-20",
    quantityAllocated: 1,
    inventory: 15,
    originalPrice: 89000,
    unit: "Electronics",
    department: "Development/Engineering",
    status: "using",
  },
  {
    id: "a002",
    code: "A002",
    name: "Dell Latitude 5440",
    group: "Laptop",
    purchaseDate: "2024-02-11",
    quantityAllocated: 8,
    inventory: 2,
    originalPrice: 98000,
    unit: "Electronics",
    department: "Development/Engineering",
    status: "using",
  },
  {
    id: "a003",
    code: "A003",
    name: "JBL Tune 510BT",
    group: "Headphone",
    purchaseDate: "2022-11-03",
    quantityAllocated: 20,
    inventory: 5,
    originalPrice: 3500,
    unit: "Piece",
    department: "Support",
    status: "not_used",
  },
  {
    id: "a004",
    code: "A004",
    name: "Ncell Corporate SIM",
    group: "SIM",
    purchaseDate: "2021-05-30",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 500,
    unit: "Card",
    department: "Admin",
    status: "using",
  },
  {
    id: "a005",
    code: "A005",
    name: "MacBook Air M2",
    group: "Laptop",
    purchaseDate: "2020-09-14",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 185000,
    unit: "Electronics",
    department: "Development/Engineering",
    status: "warranty_repair",
  },
  {
    id: "a006",
    code: "A006",
    name: "Samsung Galaxy A54",
    group: "Mobile",
    purchaseDate: "2023-01-18",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 45000,
    unit: "Electronics",
    department: "Field Reports",
    status: "report_lost",
  },
  {
    id: "a007",
    code: "A007",
    name: "Sony WH-CH520",
    group: "Headphone",
    purchaseDate: "2019-07-02",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 4500,
    unit: "Piece",
    department: "Admin",
    status: "broken",
  },
  {
    id: "a008",
    code: "A008",
    name: "NTC Corporate SIM",
    group: "SIM",
    purchaseDate: "2020-03-05",
    quantityAllocated: 1,
    inventory: 0,
    originalPrice: 300,
    unit: "Card",
    department: "Admin",
    status: "liquidation",
  },
];

export const ASSET_STATUS_LABEL: Record<Asset["status"], string> = {
  not_used: "Not used yet",
  using: "Using",
  liquidation: "Liquidation",
  warranty_repair: "Warranty Repair",
  report_lost: "Report lost",
  broken: "Broken",
};
